### ISSUE TITLE
repo structure

### ISSUE THREAD

**Issue by tobibeer** [mklauber/tiddly-mathjs#2]
Hi @mklauber, may I suggest you modify your repo structure like so:
- **plugins**
  - mklauber
    - math.js
      - _plugin.info_
- **editions**
  - math.js
    - _tiddlywiki.info_
    - tiddlers

This will ensure better interoperability with other wikis / wiki folders as you would follow the folder conventions of [the tiddlywiki repo](https://github.com/Jermolene/TiddlyWiki5/), on which it's CLI commands depend (to some degree).

The way you have set up your **tiddlywiki.info** should not actually allow you to build the wiki, even though the server interestingly manages to find the plugin.

What should also not work right now is to set an [environment variable](http://tiddlywiki.com/#Environment%20Variables%20on%20Node.js) pointing to your current plugins folder in `TIDDLYWIKI_PLUGIN_PATH`. Another wiki will not find any **mklauber/math.js** plugin by using a copy of your repo folder.

The above modifications would cater for that.

**Comment by tobibeer** [comment]
Also, if you use a **tiddlywiki.info** as I do for [dict](https://github.com/tobibeer/tw5-dict/blob/master/editions/dict/tiddlywiki.info), you will be able to simply output an index.html by running the `--build` command from your editions folder... which will be placed into your repo root folder.

Notice how I use the "$:/plugins/tiddlywiki/tiddlyweb/save/offline" template so as to not save the server plugins with it.

**Comment by mklauber** [comment]
Will do.

**Comment by tobibeer** [comment]
Thank's a lot, @mklauber. I'll try to fiddle with a macro on prerelease.

**Comment by mklauber** [comment]
Look go to you?

**Comment by tobibeer** [comment]
Very much so. Thanks a lot. :+1:
