### ISSUE TITLE
docs appear outdated

### ISSUE THREAD

**Issue by tobibeer** [mklauber/tiddly-mathjs#4]
Not sure if this is the current address: http://www.mklauber.com/mathjs.html

It appears to be using an outdated version of the plugin... and would possibly benefit from basic documentation / examples. Thanks!

**Comment by mklauber** [comment]
The current address is http://mklauber.github.io/tiddly-mathjs/

**Comment by tobibeer** [comment]
thx

**Comment by tobibeer** [comment]
@mklauber, perhaps edit / update the link in this group post (or redirect):

https://groups.google.com/d/msg/tiddlywiki/cPq72e4x1f8/x_7WoTKaAwAJ
